//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsoEticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.UrunResim = new HashSet<UrunResim>();
        }
    
        public int ID { get; set; }
        public string Baslik { get; set; }
        public string AltBaslik { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public Nullable<double> IndirimTutari { get; set; }
        public Nullable<double> IndirimliFiyat { get; set; }
        public Nullable<int> MarkaID { get; set; }
        public string Url { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> StokMiktar { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Markalar Markalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunResim> UrunResim { get; set; }
    }
}
