//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsoEticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeAdres
    {
        public int ID { get; set; }
        public int UyeID { get; set; }
        public string AdresBaslik { get; set; }
        public Nullable<int> IlID { get; set; }
        public Nullable<int> IlceID { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string PostaKodu { get; set; }
    
        public virtual Uye Uye { get; set; }
    }
}
